import { prisma } from '../lib/prisma';

// Datos de alimentos comunes con sus propiedades nutricionales
const foods = [
  // PROTEÍNAS
  {
    name: 'Pechuga de pollo',
    category: 'protein',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    potassium: 256,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['carne', 'pollo', 'bajo en grasa']
  },
  {
    name: 'Salmón',
    category: 'protein',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    potassium: 363,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pescado', 'omega-3', 'saludable']
  },
  {
    name: 'Atún en agua',
    category: 'protein',
    calories: 109,
    protein: 25,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    sugar: 0,
    sodium: 303,
    potassium: 237,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pescado', 'enlatado', 'bajo en grasa']
  },
  {
    name: 'Huevo',
    category: 'protein',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
    potassium: 126,
    commonPortionSize: 50,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['desayuno', 'versátil']
  },
  {
    name: 'Tofu',
    category: 'protein',
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    sugar: 0.7,
    sodium: 7,
    potassium: 121,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['vegano', 'soja', 'alternativa carne']
  },

  // CARBOHIDRATOS
  {
    name: 'Arroz integral',
    category: 'carb',
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 5,
    potassium: 79,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['grano entero', 'fibra']
  },
  {
    name: 'Pasta integral',
    category: 'carb',
    calories: 124,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 4.2,
    sugar: 0.8,
    sodium: 3,
    potassium: 62,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['grano entero', 'fibra']
  },
  {
    name: 'Avena',
    category: 'carb',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0,
    sodium: 2,
    potassium: 429,
    commonPortionSize: 40,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['desayuno', 'grano entero', 'fibra']
  },
  {
    name: 'Quinoa',
    category: 'carb',
    calories: 120,
    protein: 4.4,
    carbs: 22,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 7,
    potassium: 172,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pseudocereal', 'proteína vegetal', 'sin gluten']
  },
  {
    name: 'Pan integral',
    category: 'carb',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 4.2,
    fiber: 7,
    sugar: 6,
    sodium: 603,
    potassium: 230,
    commonPortionSize: 40,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['grano entero', 'fibra', 'sándwich']
  },

  // VERDURAS
  {
    name: 'Brócoli',
    category: 'vegetable',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 33,
    potassium: 316,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['crucíferas', 'verde', 'vitamina C']
  },
  {
    name: 'Espinacas',
    category: 'vegetable',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    potassium: 558,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['verde', 'hierro', 'hoja verde']
  },
  {
    name: 'Zanahoria',
    category: 'vegetable',
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
    potassium: 320,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['naranja', 'vitamina A', 'crudo', 'cocido']
  },
  {
    name: 'Tomate',
    category: 'vegetable',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
    potassium: 237,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['rojo', 'ensalada', 'licopeno']
  },
  {
    name: 'Pimiento',
    category: 'vegetable',
    calories: 20,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    fiber: 1.7,
    sugar: 2.4,
    sodium: 2,
    potassium: 175,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['rojo', 'verde', 'amarillo', 'vitamina C']
  },

  // FRUTAS
  {
    name: 'Manzana',
    category: 'fruit',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 1,
    potassium: 107,
    commonPortionSize: 150,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['fruta', 'snack', 'fibra']
  },
  {
    name: 'Plátano',
    category: 'fruit',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 1,
    potassium: 358,
    commonPortionSize: 120,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['fruta', 'potasio', 'energía']
  },
  {
    name: 'Fresas',
    category: 'fruit',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
    potassium: 153,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['fruta', 'baya', 'antioxidantes']
  },

  // LÁCTEOS
  {
    name: 'Leche desnatada',
    category: 'dairy',
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    sugar: 5,
    sodium: 44,
    potassium: 156,
    commonPortionSize: 250,
    commonPortionUnit: 'ml',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['lácteo', 'calcio', 'proteína']
  },
  {
    name: 'Yogur griego',
    category: 'dairy',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.6,
    sodium: 36,
    potassium: 141,
    commonPortionSize: 150,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['lácteo', 'proteína', 'probiótico']
  },
  {
    name: 'Queso cottage',
    category: 'dairy',
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 364,
    potassium: 104,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['lácteo', 'proteína', 'bajo en grasa']
  },

  // GRASAS SALUDABLES
  {
    name: 'Aguacate',
    category: 'fat',
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    sugar: 0.7,
    sodium: 7,
    potassium: 485,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['grasa saludable', 'monoinsaturada', 'fibra']
  },
  {
    name: 'Almendras',
    category: 'nut',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 1,
    potassium: 733,
    commonPortionSize: 30,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: false,
    tags: ['fruto seco', 'proteína vegetal', 'snack']
  },
  {
    name: 'Aceite de oliva',
    category: 'fat',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    potassium: 1,
    commonPortionSize: 15,
    commonPortionUnit: 'ml',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['grasa saludable', 'monoinsaturada', 'cocinar']
  },
  // CARBOHIDRATOS ADICIONALES
  {
    name: 'Arroz integral',
    category: 'carb',
    calories: 111,
    protein: 2.6,
    carbs: 22,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 5,
    potassium: 43,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['arroz', 'integral', 'carbohidrato complejo']
  },
  {
    name: 'Pasta integral',
    category: 'carb',
    calories: 124,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 4.6,
    sugar: 1.8,
    sodium: 3,
    potassium: 44,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pasta', 'integral', 'carbohidrato']
  },
  {
    name: 'Batata',
    category: 'carb',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 54,
    potassium: 337,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['batata', 'tubérculo', 'carbohidrato']
  },
  // PROTEÍNAS ADICIONALES
  {
    name: 'Pavo',
    category: 'protein',
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    fiber: 0,
    sugar: 0,
    sodium: 63,
    potassium: 325,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pavo', 'carne magra', 'proteína']
  },
  {
    name: 'Lentejas',
    category: 'protein',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 2,
    potassium: 369,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['lentejas', 'legumbre', 'proteína vegetal']
  },
  {
    name: 'Garbanzos',
    category: 'protein',
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 7,
    potassium: 291,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['garbanzos', 'legumbre', 'proteína vegetal']
  },
  // LÁCTEOS Y ALTERNATIVAS
  {
    name: 'Yogur griego',
    category: 'dairy',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.6,
    sodium: 36,
    potassium: 141,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['yogur', 'griego', 'proteína', 'probióticos']
  },
  {
    name: 'Queso cottage',
    category: 'dairy',
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 364,
    potassium: 104,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['queso', 'cottage', 'proteína', 'bajo en grasa']
  },
  // FRUTOS SECOS Y SEMILLAS
  {
    name: 'Almendras',
    category: 'nut',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    sugar: 4.4,
    sodium: 1,
    potassium: 733,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: false,
    tags: ['almendras', 'frutos secos', 'grasas saludables']
  },
  {
    name: 'Nueces',
    category: 'nut',
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 2,
    potassium: 441,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: false,
    tags: ['nueces', 'frutos secos', 'omega-3']
  },
  // ALIMENTOS DE DESAYUNO ADICIONALES
  {
    name: 'Leche entera',
    category: 'dairy',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 4.8,
    sodium: 44,
    potassium: 150,
    commonPortionSize: 250,
    commonPortionUnit: 'ml',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['leche', 'desayuno', 'calcio']
  },
  {
    name: 'Mantequilla de maní',
    category: 'nut',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    sugar: 9,
    sodium: 17,
    potassium: 649,
    commonPortionSize: 32,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: false,
    tags: ['mantequilla de maní', 'desayuno', 'proteína']
  },
  {
    name: 'Cereales integrales',
    category: 'grain',
    calories: 379,
    protein: 8,
    carbs: 84,
    fat: 2.3,
    fiber: 7,
    sugar: 4,
    sodium: 729,
    potassium: 169,
    commonPortionSize: 40,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['cereales', 'desayuno', 'fibra']
  },
  {
    name: 'Miel',
    category: 'sweetener',
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    sugar: 82,
    sodium: 4,
    potassium: 52,
    commonPortionSize: 21,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['miel', 'endulzante', 'natural']
  },
  // FRUTAS ADICIONALES
  {
    name: 'Manzana',
    category: 'fruit',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    potassium: 107,
    commonPortionSize: 182,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['manzana', 'fruta', 'fibra']
  },
  {
    name: 'Naranja',
    category: 'fruit',
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9,
    sodium: 0,
    potassium: 181,
    commonPortionSize: 154,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['naranja', 'cítrico', 'vitamina C']
  },
  {
    name: 'Fresas',
    category: 'fruit',
    calories: 32,
    protein: 0.7,
    carbs: 8,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
    potassium: 153,
    commonPortionSize: 152,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['fresas', 'berries', 'antioxidantes']
  },
  // PROTEÍNAS ADICIONALES
  {
    name: 'Jamón de pavo',
    category: 'protein',
    calories: 109,
    protein: 17,
    carbs: 1.5,
    fat: 3.5,
    fiber: 0,
    sugar: 1.2,
    sodium: 1047,
    potassium: 287,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['jamón', 'pavo', 'bajo en grasa']
  },
  {
    name: 'Ricotta',
    category: 'dairy',
    calories: 174,
    protein: 11,
    carbs: 3,
    fat: 13,
    fiber: 0,
    sugar: 0.3,
    sodium: 84,
    potassium: 105,
    commonPortionSize: 100,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isLactoseFree: false,
    isNutFree: true,
    tags: ['ricotta', 'queso', 'cremoso']
  },
  // VEGETALES ADICIONALES
  {
    name: 'Pepino',
    category: 'vegetable',
    calories: 16,
    protein: 0.7,
    carbs: 4,
    fat: 0.1,
    fiber: 1.5,
    sugar: 1.7,
    sodium: 2,
    potassium: 147,
    commonPortionSize: 119,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pepino', 'hidratante', 'bajo en calorías']
  },
  {
    name: 'Zanahoria',
    category: 'vegetable',
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
    potassium: 320,
    commonPortionSize: 61,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['zanahoria', 'vitamina A', 'betacaroteno']
  },
  {
    name: 'Pimiento rojo',
    category: 'vegetable',
    calories: 31,
    protein: 1,
    carbs: 7,
    fat: 0.3,
    fiber: 2.5,
    sugar: 4.2,
    sodium: 4,
    potassium: 211,
    commonPortionSize: 119,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['pimiento', 'vitamina C', 'colorido']
  },
  // CARBOHIDRATOS ADICIONALES
  {
    name: 'Tortilla de trigo',
    category: 'carb',
    calories: 218,
    protein: 6,
    carbs: 36,
    fat: 5.7,
    fiber: 2.3,
    sugar: 1.2,
    sodium: 400,
    potassium: 92,
    commonPortionSize: 49,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['tortilla', 'wrap', 'versátil']
  },
  // MÁS ALIMENTOS DE DESAYUNO
  {
    name: 'Granola',
    category: 'grain',
    calories: 471,
    protein: 10,
    carbs: 64,
    fat: 20,
    fiber: 6,
    sugar: 21,
    sodium: 24,
    potassium: 336,
    commonPortionSize: 50,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isLactoseFree: true,
    isNutFree: false,
    tags: ['granola', 'desayuno', 'crujiente']
  },
  {
    name: 'Kiwi',
    category: 'fruit',
    calories: 61,
    protein: 1.1,
    carbs: 15,
    fat: 0.5,
    fiber: 3,
    sugar: 9,
    sodium: 3,
    potassium: 312,
    commonPortionSize: 76,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['kiwi', 'vitamina C', 'tropical']
  },
  {
    name: 'Arándanos',
    category: 'fruit',
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    potassium: 77,
    commonPortionSize: 148,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['arándanos', 'berries', 'antioxidantes']
  },
  {
    name: 'Semillas de chía',
    category: 'seed',
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    fiber: 34,
    sugar: 0,
    sodium: 16,
    potassium: 407,
    commonPortionSize: 12,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['chía', 'semillas', 'omega-3', 'fibra']
  },
  {
    name: 'Coco rallado',
    category: 'nut',
    calories: 354,
    protein: 3.3,
    carbs: 15,
    fat: 33,
    fiber: 9,
    sugar: 6,
    sodium: 20,
    potassium: 356,
    commonPortionSize: 80,
    commonPortionUnit: 'g',
    alternativesIds: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isLactoseFree: true,
    isNutFree: true,
    tags: ['coco', 'tropical', 'grasas saludables']
  }
];

export async function seedFoods() {
  try {
    console.log('🌱 Iniciando seed de alimentos...');

    // Limpiar alimentos existentes (opcional)
    console.log('🧹 Limpiando alimentos existentes...');
    await prisma.mealIngredient.deleteMany();
    await prisma.recipeItem.deleteMany();
    await prisma.food.deleteMany();

    // Crear alimentos
    console.log('🥕 Creando alimentos...');
    const createdFoods = await Promise.all(
      foods.map(food =>
        prisma.food.upsert({
          where: { name: food.name },
          update: food,
          create: food
        })
      )
    );
    console.log(`✅ ${createdFoods.length} alimentos creados`);

    // Actualizar alternativas (ahora que tenemos IDs)
    console.log('🔄 Actualizando alternativas entre alimentos...');

    // Ejemplo: establecer tofu como alternativa a la pechuga de pollo para vegetarianos
    const tofu = createdFoods.find((i: any) => i.name === 'Tofu');
    const chicken = createdFoods.find((i: any) => i.name === 'Pechuga de pollo');

    if (tofu && chicken) {
      await prisma.food.update({
        where: { id: chicken.id },
        data: {
          alternativesIds: [tofu.id]
        }
      });

      console.log('✅ Alternativas actualizadas');
    }

    console.log('🎉 Seed de alimentos completado exitosamente!');
    return createdFoods;
  } catch (error: any) {
    console.error('❌ Error durante el seed de alimentos:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Ejecutar el seed si este archivo se ejecuta directamente
if (require.main === module) {
  seedFoods()
    .then(() => {
      console.log('Seed de alimentos ejecutado exitosamente');
      process.exit(0);
    })
    .catch((error: any) => {
      console.error('Error ejecutando seed de alimentos:', error);
      process.exit(1);
    });
}